export type color = {
  r: number
  g: number
  b: number
}

export const hex = (c: color): string =>
  `#${[c.r, c.g, c.b].map((v) => v.toString(16).padStart(2, '0')).join('')}`

// Pre-defined colors (generated by copilot)
export const colors = {
  red: { r: 255, g: 0, b: 0 },
  green: { r: 0, g: 255, b: 0 },
  blue: { r: 0, g: 0, b: 255 },
  yellow: { r: 0, g: 255, b: 255 },
  purple: { r: 255, g: 0, b: 255 },
  cyan: { r: 255, g: 255, b: 0 },
  white: { r: 255, g: 255, b: 255 },
  black: { r: 0, g: 0, b: 0 },
  gray: { r: 128, g: 128, b: 128 },
  orange: { r: 255, g: 128, b: 0 },
  pink: { r: 255, g: 0, b: 128 },
  lightgreen: { r: 128, g: 255, b: 128 },
  lightblue: { r: 128, g: 128, b: 255 },
  lightyellow: { r: 128, g: 255, b: 255 },
  lightpurple: { r: 255, g: 128, b: 255 },
  lightcyan: { r: 255, g: 255, b: 128 },
  lightorange: { r: 255, g: 192, b: 128 },
  lightpink: { r: 255, g: 128, b: 192 },
  darkgreen: { r: 0, g: 128, b: 0 },
  darkblue: { r: 0, g: 0, b: 128 },
  darkyellow: { r: 0, g: 128, b: 128 },
  darkpurple: { r: 128, g: 0, b: 128 },
  darkcyan: { r: 128, g: 128, b: 0 },
  darkorange: { r: 128, g: 64, b: 0 },
}
